/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ColImport } from './routes/col'
import { Route as CardImport } from './routes/card'
import { Route as ButtonImport } from './routes/button'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ColRoute = ColImport.update({
  path: '/col',
  getParentRoute: () => rootRoute,
} as any)

const CardRoute = CardImport.update({
  path: '/card',
  getParentRoute: () => rootRoute,
} as any)

const ButtonRoute = ButtonImport.update({
  path: '/button',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonImport
      parentRoute: typeof rootRoute
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardImport
      parentRoute: typeof rootRoute
    }
    '/col': {
      id: '/col'
      path: '/col'
      fullPath: '/col'
      preLoaderRoute: typeof ColImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ButtonRoute,
  CardRoute,
  ColRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/button",
        "/card",
        "/col"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/button": {
      "filePath": "button.tsx"
    },
    "/card": {
      "filePath": "card.tsx"
    },
    "/col": {
      "filePath": "col.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
